project/__init__.py
# project/__init__.py


#################
#### imports ####
#################

# import os

from flask import Flask, render_template
from flask.ext.login import LoginManager
from flask.ext.bcrypt import Bcrypt
from flask_mail import Mail
from flask.ext.debugtoolbar import DebugToolbarExtension
from flask.ext.sqlalchemy import SQLAlchemy

################
#### config ####
################

app = Flask(__name__)

app.config.from_object('project.config.ProductionConfig')

####################
#### extensions ####
####################

login_manager = LoginManager()
login_manager.init_app(app)
bcrypt = Bcrypt(app)
mail = Mail(app)
toolbar = DebugToolbarExtension(app)
db = SQLAlchemy(app)


####################
#### blueprints ####
####################

from project.main.views import main_blueprint
from project.user.views import user_blueprint
app.register_blueprint(main_blueprint)
app.register_blueprint(user_blueprint)


####################
#### flask-login ####
####################

from project.models import User

login_manager.login_view = "user.login"
login_manager.login_message_category = "danger"


@login_manager.user_loader
def load_user(user_id):
    return User.query.filter(User.id == int(user_id)).first()


########################
#### error handlers ####
########################

@app.errorhandler(403)
def forbidden_page(error):
    return render_template("errors/403.html"), 403


@app.errorhandler(404)
def page_not_found(error):
    return render_template("errors/404.html"), 404


@app.errorhandler(500)
def server_error_page(error):
    return render_template("errors/500.html"), 500

project/main/views.py
# project/main/views.py


#################
#### imports ####
#################

from flask import render_template, Blueprint
from flask.ext.login import login_required


################
#### config ####
################

main_blueprint = Blueprint('main', __name__,)


################
#### routes ####
################

@main_blueprint.route('/')
@login_required
def home():
    return render_template('main/index.html')

project/user/views.py
# project/user/views.py


#################
#### imports ####
#################
import datetime

from flask import render_template, Blueprint, url_for, redirect, flash, request
from flask.ext.login import login_user, logout_user, login_required, current_user

from sqlalchemy import desc

from project.token import generate_confirmation_token, confirm_token
from project.decorators import check_confirmed
from project.email import send_email
from project import db, bcrypt

from project.models import (
    User,
    Employment,
    Education,
    Publication,
    Patent
)

from .forms import (
    LoginForm,
    RegisterForm,
    ChangePasswordForm,
    EmploymentForm,
    EmploymentListForm,
    EducationForm,
    EducationFormListForm,
    EditPersonalForm,
    PublicationForm,
    PublicationFormListForm,
    PatentForm,
    PatentFormListForm
)


################
#### config ####
################

user_blueprint = Blueprint('user', __name__,)


################
#### routes ####
################

@user_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)

    if form.validate_on_submit():
        user = User(
            email=form.email.data,
            password=form.password.data,
            confirmed=False
        )
        db.session.add(user)
        db.session.commit()

        token = generate_confirmation_token(user.email)
        confirm_url = url_for('user.confirm_email', token=token, _external=True)
        html = render_template('user/activate.html', confirm_url=confirm_url)
        subject = "Please confirm your email"
        send_email(user.email, subject, html)

        login_user(user)
        flash('You registered and are now logged in. Welcome!', 'success')

        return redirect(url_for('user.unconfirmed'))

    return render_template('user/register.html', form=form)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user and bcrypt.check_password_hash(
                user.password, request.form['password']):
            login_user(user)
            flash('Welcome.', 'success')
            return redirect(url_for('user.profile', username=user.username))
        else:
            flash('Invalid email and/or password.', 'danger')
            return render_template('user/login.html', form=form)

    return render_template('user/login.html', form=form)


@user_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You were logged out.', 'success')
    return redirect(url_for('user.login'))


@user_blueprint.route('/changepassword', methods=['GET', 'POST'])
@login_required
@check_confirmed
def changepassword():
    user = User.query.filter_by(email=current_user.email).first()
    if not user:
        flash('Password successfully changed.', 'success')
        return redirect(url_for('user.logout'))

    form = ChangePasswordForm(request.form, prefix='pwd')
    if form.validate_on_submit():
        user = User.query.filter_by(email=current_user.email).first()
        if user:
            user.password = bcrypt.generate_password_hash(form.password.data)
            db.session.commit()
            flash('Password successfully changed.', 'success')
            return redirect(url_for('user.profile', username=user.username))
        else:
            flash('Password change was unsuccessful.', 'danger')
            return redirect(url_for('user.changepassword'))

    return render_template('user/changepassword.html', form=form)


@user_blueprint.route('/confirm/<token>')
@login_required
def confirm_email(token):
    try:
        email = confirm_token(token)
    except:
        flash('The confirmation link is invalid or has expired.', 'danger')

    user = User.query.filter_by(email=email).first_or_404()

    if user.confirmed:
        flash('Account already confirmed. Please login.', 'success')
    else:
        user.confirmed = True
        user.confirmed_on = datetime.datetime.now()
        db.session.add(user)
        db.session.commit()
        flash('You have confirmed your account. Thanks!', 'success')

    return redirect(url_for('main.home'))


@user_blueprint.route('/unconfirmed')
@login_required
def unconfirmed():
    if current_user.confirmed:
        return redirect('main.home')
    flash('Please confirm your account!', 'warning')
    return render_template('user/unconfirmed.html')


@user_blueprint.route('/resend')
@login_required
def resend_confirmation():
    token = generate_confirmation_token(current_user.email)
    confirm_url = url_for('user.confirm_email', token=token, _external=True)
    html = render_template('user/activate.html', confirm_url=confirm_url)
    subject = "Please confirm your email"
    send_email(current_user.email, subject, html)
    flash('A new confirmation email has been sent.', 'success')
    return redirect(url_for('user.unconfirmed'))


@user_blueprint.route('/user/<username>')
@login_required
def profile(username):
    user = User.query.filter_by(username=username).first()
    if user == None:
        flash('User %s not found.' % username, 'danger')
        return redirect(url_for('main.home'))

    form = EditPersonalForm(request.form)

    return render_template('user/profile.html', user=user, form=form)


@user_blueprint.route('/user_edit_firstname', methods=['POST'])
@login_required
def user_edit_firstname():
    user = User.query.filter_by(email=current_user.email).first()
    user.firstname = request.form['value']
    db.session.commit()
    return redirect(url_for('user.profile', username=user.username))


@user_blueprint.route('/user_edit_lasttname', methods=['POST'])
@login_required
def user_edit_lastname():
    user = User.query.filter_by(email=current_user.email).first()
    user.surname = request.form['value']
    db.session.commit()
    return redirect(url_for('user.profile', username=user.username))


@user_blueprint.route('/user_edit_dob', methods=['POST'])
@login_required
def user_edit_dob():
    user = User.query.filter_by(email=current_user.email).first()
    user.birthdate = request.form['value']
    db.session.commit()
    return redirect(url_for('user.profile', username=user.username))


@user_blueprint.route('/user_edit_gender', methods=['POST'])
@login_required
def user_edit_gender():
    user = User.query.filter_by(email=current_user.email).first()
    user.gender = request.form['value']
    db.session.commit()
    return redirect(url_for('user.profile', username=user.username))


@user_blueprint.route('/user/employment_add/<human_id>',
                      methods=['GET', 'POST'])
@login_required
def employment_add(human_id):
    user = User.query.filter_by(id=human_id).first()
    if user == None:
        flash('User not found.', 'danger')
        return redirect(url_for('main.home'))

    form = EmploymentForm(request.form)

    if form.validate_on_submit():
        start_date = None
        end_date = None

        if request.form["start_date"] != '':
            start_date = request.form["start_date"]

        if request.form["end_date"] != '':
            end_date = request.form["end_date"]

        emp = Employment(
            human_id=human_id,
            employer=request.form["employer"],
            position=request.form["position"],
            start_date=start_date ,
            end_date=end_date,
            job_desc=request.form["job_desc"]
        )
        db.session.add(emp)
        db.session.commit()
        flash('New employer added.', 'success')
        return redirect(url_for('user.employment_list', human_id=human_id))

    if form.errors:
        print(form.errors)

    return render_template('user/employment_add.html', username=user.username,
                           email=user.email, form=form, human_id=human_id)


@user_blueprint.route('/employment_list/<human_id>', methods=['GET'])
@login_required
def employment_list(human_id):
    user = User.query.filter_by(id=human_id).first()
    if user == None:
        flash('User not found', 'danger')
        return redirect(url_for('main.home'))

    emp = Employment.query.filter_by(human_id=user.id).order_by(
        desc(Employment.start_date))

    if emp == None:
        flash('No employment details saved', 'danger')

    data = {'employmentlist': emp}
    form = EmploymentListForm(data=data)

    return render_template('user/employment_list.html', form=form,
                           human_id=user.id)


@user_blueprint.route('/employment_edit/<emp_id>', methods=['GET'])
@login_required
def employment_edit(emp_id):
    emp = Employment.query.filter_by(id=emp_id).first()
    if emp == None:
        flash('No Employment Details.  Please add', 'danger')
        return redirect(url_for('user.employment_add',
                                human_id=current_user.id))

    return render_template('user/employment_edit.html', emp=emp)


@user_blueprint.route('/employment_edit_employer/<emp_id>', methods=['POST'])
@login_required
def employment_edit_employer(emp_id):
    emp = Employment.query.filter_by(id=emp_id).first()
    emp.employer = request.form['value']
    db.session.commit()
    return redirect(url_for('user.employment_list', human_id=emp.human_id))


@user_blueprint.route('/employment_edit_position/<emp_id>', methods=['POST'])
@login_required
def employment_edit_position(emp_id):
    emp = Employment.query.filter_by(id=emp_id).first()
    emp.position = request.form['value']
    db.session.commit()
    return redirect(url_for('user.employment_list', human_id=emp.human_id))


@user_blueprint.route('/employment_edit_description/<emp_id>',
                      methods=['POST'])
@login_required
def employment_edit_description(emp_id):
    emp = Employment.query.filter_by(id=emp_id).first()
    emp.job_desc = request.form['value']
    db.session.commit()

project/templates/_base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Flask User Management</title>
    <!-- meta -->
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- styles -->
    <link href="http://maxcdn.bootstrapcdn.com/bootswatch/3.2.0/yeti/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="{{url_for('static', filename='main.css')}}" rel="stylesheet" media="screen">
    <link href="{{url_for('static', filename='bootstrap-editable.css')}}" rel="stylesheet" media="screen">
    {% block css %}{% endblock %}
  </head>
  <body>

    {% include "navigation.html" %}

    <div class="container">

      <br>

      <!-- messages -->
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
      <div class="row">
        <div class="col-md-12">
          {% for category, message in messages %}
          <div class="alert alert-{{ category }}">
            <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
           {{message}}
          </div>
          {% endfor %}
        </div>
      </div>
      {% endif %}
      {% endwith %}

      <!-- child template -->
      {% block content %}{% endblock %}

      <br>

      <!-- errors -->
      {% if error %}
        <p class="error"><strong>Error:</strong> {{ error }}</p>
      {% endif %}

    </div>

    <!-- scripts -->
    <script src="https://code.jquery.com/jquery-2.1.1.min.js" type="text/javascript"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="{{url_for('static', filename='main.js')}}" type="text/javascript"></script>
    <script src="{{url_for('static', filename='bootstrap-editable.js')}}" type="text/javascript"></script>
    {% block js %}{% endblock %}

  </body>
</html>

project/templates/navigation.html
<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ url_for('main.home') }}">{{ current_user.email }}</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        {% if current_user.confirmed and current_user.is_authenticated() %}
          <li><a href="{{ url_for('user.profile', username=current_user.username) }}">Profile</a></li>
          <li class="dropdown">
            <a data-toggle="dropdown" class="dropdown-toggle disabled" href="{{ url_for('user.academic_record', human_id=current_user.id) }}">Academic Record<b class="caret"></b></a>
            <ul class="dropdown-menu">
            <li><a href="{{ url_for('user.education_list', human_id=current_user.id) }}">Education</a></li>
            <li><a href="{{ url_for('user.patent_list', human_id=current_user.id) }}">Patents</a></li>
            <li><a href="{{ url_for('user.publication_list', human_id=current_user.id) }}">Publications</a></li>
            </ul>
          </li>
          <li><a href="{{ url_for('user.employment_list', human_id=current_user.id) }}">Employment History</a></li>

          <link href="{{url_for('static', filename='bootstrap-editable.css')}}" rel="stylesheet" media="screen">
          <script src="http://code.jquery.com/jquery-2.0.3.min.js"></script>
          <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
          <script src="{{url_for('static', filename='bootstrap-editable.js')}}" type="text/javascript"></script>

        {% elif current_user.is_authenticated() %}
          <li><a href="{{ url_for('user.unconfirmed') }}">Confirm</a></li>
        {% endif %}
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if current_user.is_authenticated() %}
          <li><a href="{{ url_for('user.logout') }}">Logout</a></li>
        {% else %}
          <li><a href="{{ url_for('user.register') }}">Sign up</a></li>
          <li><a href="{{ url_for('user.login') }}"><span class="glyphicon glyphicon-user"></span>&nbsp;Login</a></li>
        {% endif %}
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

project/templates/unconfirmed.html
{% extends "_base.html" %}

{% block content %}

<h1>Welcome!</h1>
<br>
<p>You have not confirmed your account. Please check your inbox (and your spam folder) - you should have received an email with a confirmation link.</p>
<p>Didn't get the email? <a href="{{ url_for('user.resend_confirmation') }}">Resend</a>.</p>

{% endblock %}